- hosts: localhost  
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False 

  tasks:
    - include_vars: users_var.yml
    - include_vars: logrotate_var.yml
    - include_tasks: apt.yml
    - include_tasks: firewall.yml
    - include_tasks: sudoers.yml
    - include_tasks: groups.yml
    - include_tasks: users.yml
    - include_tasks: authorized_keys.yml
    - include_tasks: cron.yml
    - include_tasks: sshd.yml
    - include_tasks: logrotate.yml