## hosts set to localhost for ansible-pull
## usually ansible works by pushing from the server to the client
- hosts: localhost  
  connection: local
  become: true

## run these tasks before others
## gets apt cache in order
  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False 

## complete these tasks as part of the playbook
## use variables where required
  tasks:
    - include_vars: users_var.yml
    - include_vars: logrotate_var.yml
    - include_vars: 
        file: netplan_var.yml
        name: netplan_conf
    - include_tasks: tasks/apt.yml
    - include_tasks: tasks/firewall.yml
    - include_tasks: tasks/sudoers.yml
    - include_tasks: tasks/groups.yml
    - include_tasks: tasks/users.yml
    - include_tasks: tasks/authorized_keys.yml
    - include_tasks: tasks/cron.yml
    - include_tasks: tasks/sshd.yml
    - include_tasks: tasks/logrotate.yml
    - include_tasks: tasks/netplan.yml