- hosts: localhost  
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False 

  tasks:
    - include_vars: users_var.yml
    - include_vars: authorized_keys_var.yml
    - include: tasks/apt.yml
    - include: tasks/firewall.yml
    - include: tasks/sudoers.yml
    - include: tasks/groups.yml
    - include: tasks/users.yml
    - include: tasks/authorized_keys.yml
    - include: tasks/cron.yml
  