- hosts: localhost  
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/apt.yml
    - include: tasks/firewall.yml
    - include: tasks/sudoers.yml
    - include: tasks/groups.yml
    - include: tasks/users.yml
    - include: tasks/authorisedkeys.yml