## install unattended upgrade package 
## by default this will not automatically reboot
- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    update_cache: yes

## enable periodic updates by coping the file from this repo to the machine in the specified path
## auto reboots disabled by default
- name: Enable periodic updates 
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644