- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # every 24 hrs

- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    update_cache: yes

- name: Enable periodic updates # auto reboots disabled by default
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644