- name: Set authorized keys taken from url
  authorized_key:
    user: "{{ item.login }}"
    state: present
    key: https://raw.githubusercontent.com/SimplifyTechTeam/TeamSSHKeys/main/{{ item.login }}.pub
  loop: "{{ users }}"