- name: install ansible pull cron
  cron:
    user: sitadmin-a
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -C main -d /var/projects/ansible-bootstrap -U https://github.com/SimplifyTechTeam/LinuxBootstrap.git
    #job: "/usr/bin/ansible-pull -o -C main -d /var/projects/ansible-bootstrap -U https://github.com/SimplifyTechTeam/LinuxBootstrap.git | sudo tee -a /var/log/ansible-bootstrap.log