- name: install ansible pull cron
  cron:
    user: sitadmin-a
    name: "ansible provision"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -C main -d /var/projects/ansible-linuxbootstrap -i /var/projects/ansible-linuxbootstrap/inventory -U https://github.com/SimplifyTechTeam/LinuxBootstrap.git | tee -a /var/log/ansible-linuxbootstrap/ansible-pull.log"