## gather installed packages as facts
- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

## print installed packages
- name: Print the package facts
  ansible.builtin.debug:
    var: ansible_facts.packages