## create firewall rule for ssh ingress
## run 'sudo ufw version' to see created rule
- name: Enable ufw access for OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

## turn on firewall
- name: Enable ufw
  ufw:
    state: enabled