---
# tasks file for harden
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 # every 24 hrs

- name: Ensure sitadmin user present
  user:
    name: sitadmin
    shell: /bin/bash
    password: e1bdc49ff5b914f3d6255d9af6208466c326db2f9489d21632c7e78ba727b452fb7f1a56f69b78d7ca3b73edb8d70b64e0722bd03ae3bf71e8e87f46e9a7d065

- name: Set permissions on /home/sitadmin/.ssh
  file:
    path: /home/sitadmin/.ssh/authorized_keys
    owner: sitadmin
    group: sitadmin
    mode: 755

- name: Copy ssh public key to authorized_keys
  copy:
    src: deploy.pub
    dest: /home/sitadmin/.ssh/authorized_keys
    owner: sitadmin
    group: sitadmin
    mode: 0644

- name: Disable admin group in sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^%admin"
    line: "#%admin ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Disable sudo group in sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^%sudo"
    line: "#%sudo ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Add sitadmin to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sitadmin"
    line: "%sitadmin ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Disable root login via password
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin prohibit-password"

- name: Disable PasswordAuthentication
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"

- name: Install unattended-upgrades package
  apt:
    name: unattended-upgrades
    update_cache: yes

- name: Enable periodic updates
  copy:
    src: 10periodic
    dest: /etc/apt/apt.conf.d/10periodic
    owner: root
    group: root
    mode: 0644

- name: Enable ufw access for OpenSSH
  ufw:
    rule: allow
    name: OpenSSH

- name: Enable ufw
  ufw:
    state: enabled