- name: Disable root login via password
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin prohibit-password"

- name: Disable sudo group in sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^%sudo"
    line: "#%sudo ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Disable admin group in sudoers
  lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^%admin"
    line: "#%admin ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

#- name: Disable PasswordAuthentication
#  lineinfile:
#    path: /etc/ssh/sshd_config
#    state: present
#    regexp: "^PasswordAuthentication"
 #   line: "PasswordAuthentication no"