## creates users by looping through the users variable file
## automatically creates home directory, no password expiry, bash on login and puts them in sit-admins group
- name: Add users
  user:
    name: "{{ item.login }}"
    shell: /bin/bash
    groups: sit-admins
    create_home: true
    expires: -1
  loop: "{{ users }}"